version: '3.8'
services:
  test-db:
    image: postgres:16
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest_api_tutorial
    networks:
      - freecodecamp
networks:
  freecodecamp: